---
- hosts: lamp            # name of a list of machines in inventory file
  remote_user: ubuntu
  become: true            # gives machines sudo capabilities

  tasks:
    - name: Install packages
      - apt:
          name: "{{ item }}"            # syntax for variable rather than a single value becauuse multiple packages will be installed.
          state: present                # Means you want the packages installed
          update_cache: true            # Updates apt cache before installing anything. (good practice)
        with_items:                     # with_items: property allows you to loop over a task with its required list of arguements
          - apache2
          - mysql-server
          - mysql-common
          - mysql-client
          - libapache2-mod-wsgi

    - name: Start services
      services:                         # service module 
        name: "{{ item }}"
        state: running
      with_items:
        - apache2
        - mysql

    - name: Enable modssl
      shell: a2enmod ssl                # shell module 

    - name: Enable default HTTPS site
      shell: a2ensite defualt-ssl

    - name: Restart Apache
      service:
        name: apache2
        state: restart
    