- name: Copy app to apache owner folder 
  Ksshell: "rsync -av path {{ app_download_dest }}/app/ {{ app_dest }}"

- name: Install mod-wsgi
  apt:
    name: libapache2-mod-wsgi
    state: present

- name: Copy the apache configuration file
  template:                                               # module changed from copy to template to make changes readable in template file
    src: "apache.com"
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache                                  # calling the handler task
